// База данных бань России
// Автоматически сгенерирована

export const getBathsForCity = (citySlug) => {
  return baths[citySlug] || [];
};

const baths = {
  // ============= МОСКВА (30 бань) =============
  'moskva': [
    {
      name: 'Русская баня 1',
      types: ['Финская сауна'],
      address: 'Ленина ул., 15',
      phone: '+7 (495) 64-64-44',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1297 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.3,
      reviewCount: 47,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 4 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 2',
      types: ['Русская баня', 'С бассейном'],
      address: 'Победы ул., 20',
      phone: '+7 (495) 41-36-66',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1763 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.5,
      reviewCount: 36,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 6 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 3',
      types: ['Финская сауна'],
      address: 'Ленина ул., 25',
      phone: '+7 (495) 92-09-08',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2282 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.2,
      reviewCount: 34,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 4 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Москва 4',
      types: ['Русская баня'],
      address: 'Кирова ул., 30',
      phone: '+7 (495) 95-66-36',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1793 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.9,
      reviewCount: 23,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 9 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 5',
      types: ['Финская сауна'],
      address: 'Советская ул., 35',
      phone: '+7 (495) 35-26-83',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1923 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.9,
      reviewCount: 35,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 6 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Москва 6',
      types: ['Русская баня'],
      address: 'Ленина ул., 40',
      phone: '+7 (495) 58-50-38',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1783 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 49,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 6 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 7',
      types: ['Русская баня'],
      address: 'Ленина ул., 45',
      phone: '+7 (495) 42-01-83',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1218 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.7,
      reviewCount: 53,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 8',
      types: ['Русская баня', 'С бассейном'],
      address: 'Кирова ул., 50',
      phone: '+7 (495) 89-44-03',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2188 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.9,
      reviewCount: 45,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 9',
      types: ['Финская сауна'],
      address: 'Победы ул., 55',
      phone: '+7 (495) 27-43-57',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1857 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 38,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 6 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 10',
      types: ['Финская сауна'],
      address: 'Мира ул., 60',
      phone: '+7 (495) 42-87-80',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1463 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 16,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 4 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 11',
      types: ['Русская баня'],
      address: 'Победы ул., 65',
      phone: '+7 (495) 32-28-48',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2893 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 19,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 12 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Москва 12',
      types: ['Финская сауна'],
      address: 'Мира ул., 70',
      phone: '+7 (495) 21-46-93',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1706 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 57,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 6 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Москваская баня №13',
      types: ['Русская баня', 'С бассейном'],
      address: 'Кирова ул., 75',
      phone: '+7 (495) 36-57-03',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1804 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 25,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 14',
      types: ['Финская сауна'],
      address: 'Победы ул., 80',
      phone: '+7 (495) 56-73-67',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2339 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 27,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 11 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 15',
      types: ['Финская сауна'],
      address: 'Победы ул., 85',
      phone: '+7 (495) 26-51-11',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2771 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.4,
      reviewCount: 42,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 12 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Москваская баня №16',
      types: ['Финская сауна'],
      address: 'Мира ул., 90',
      phone: '+7 (495) 43-53-87',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1595 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.0,
      reviewCount: 42,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 17',
      types: ['Русская баня', 'С бассейном'],
      address: 'Мира ул., 95',
      phone: '+7 (495) 79-72-64',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1842 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.7,
      reviewCount: 33,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 8 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 18',
      types: ['Финская сауна'],
      address: 'Ленина ул., 100',
      phone: '+7 (495) 73-85-55',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2220 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.0,
      reviewCount: 64,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 10 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 19',
      types: ['Русская баня', 'С бассейном'],
      address: 'Мира ул., 105',
      phone: '+7 (495) 72-24-01',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1645 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.2,
      reviewCount: 22,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 10 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 20',
      types: ['Финская сауна'],
      address: 'Советская ул., 110',
      phone: '+7 (495) 82-99-38',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2517 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.2,
      reviewCount: 28,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 6 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Москваская баня №21',
      types: ['Русская баня', 'С бассейном'],
      address: 'Победы ул., 115',
      phone: '+7 (495) 58-22-27',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1895 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.5,
      reviewCount: 18,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 8 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 22',
      types: ['Финская сауна'],
      address: 'Кирова ул., 120',
      phone: '+7 (495) 72-49-91',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2996 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.4,
      reviewCount: 22,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 6 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Москваская баня №23',
      types: ['Русская баня'],
      address: 'Кирова ул., 125',
      phone: '+7 (495) 52-04-80',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2875 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 29,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 8 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 24',
      types: ['Русская баня'],
      address: 'Кирова ул., 130',
      phone: '+7 (495) 79-93-74',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2636 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 22,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Москваская баня №25',
      types: ['Русская баня'],
      address: 'Победы ул., 135',
      phone: '+7 (495) 90-19-77',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2548 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 46,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 4 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Москва 26',
      types: ['Русская баня', 'С бассейном'],
      address: 'Ленина ул., 140',
      phone: '+7 (495) 59-63-15',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2568 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.3,
      reviewCount: 32,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 8 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Москваская баня №27',
      types: ['Русская баня', 'С бассейном'],
      address: 'Советская ул., 145',
      phone: '+7 (495) 49-18-60',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1736 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.3,
      reviewCount: 32,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 28',
      types: ['Русская баня', 'С бассейном'],
      address: 'Кирова ул., 150',
      phone: '+7 (495) 72-42-92',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1720 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.2,
      reviewCount: 35,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 11 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 29',
      types: ['Русская баня'],
      address: 'Победы ул., 155',
      phone: '+7 (495) 42-81-61',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1458 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.3,
      reviewCount: 54,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 9 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 30',
      types: ['Русская баня', 'С бассейном'],
      address: 'Мира ул., 160',
      phone: '+7 (495) 83-05-00',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2544 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.4,
      reviewCount: 61,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 9 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    }
  ],

  // ============= САНКТ-ПЕТЕРБУРГ (25 бань) =============
  'sankt-peterburg': [
    {
      name: 'Санкт-Петербургская баня №1',
      types: ['Русская баня'],
      address: 'Победы ул., 15',
      phone: '+7 (812) 97-07-61',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2085 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 33,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 10 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 2',
      types: ['Русская баня', 'С бассейном'],
      address: 'Мира ул., 20',
      phone: '+7 (812) 46-65-14',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2633 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 52,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 12 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Санкт-Петербург 3',
      types: ['Финская сауна'],
      address: 'Кирова ул., 25',
      phone: '+7 (812) 73-35-85',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1907 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.4,
      reviewCount: 23,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Санкт-Петербург 4',
      types: ['Русская баня'],
      address: 'Победы ул., 30',
      phone: '+7 (812) 42-47-54',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1573 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 37,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 6 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Санкт-Петербургская баня №5',
      types: ['Русская баня'],
      address: 'Кирова ул., 35',
      phone: '+7 (812) 36-59-82',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1685 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 5.0,
      reviewCount: 15,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 10 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Санкт-Петербург 6',
      types: ['Русская баня'],
      address: 'Кирова ул., 40',
      phone: '+7 (812) 62-59-23',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2668 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.5,
      reviewCount: 31,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 10 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 7',
      types: ['Русская баня'],
      address: 'Ленина ул., 45',
      phone: '+7 (812) 94-15-11',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1521 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.8,
      reviewCount: 55,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 12 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Санкт-Петербург 8',
      types: ['Русская баня', 'С бассейном'],
      address: 'Победы ул., 50',
      phone: '+7 (812) 31-36-71',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1811 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 56,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 9',
      types: ['Русская баня'],
      address: 'Советская ул., 55',
      phone: '+7 (812) 27-28-53',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1263 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.5,
      reviewCount: 43,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 12 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 10',
      types: ['Русская баня', 'С бассейном'],
      address: 'Кирова ул., 60',
      phone: '+7 (812) 56-06-62',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2807 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 30,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 8 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 11',
      types: ['Русская баня'],
      address: 'Ленина ул., 65',
      phone: '+7 (812) 44-43-43',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1911 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 5.0,
      reviewCount: 53,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 11 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 12',
      types: ['Русская баня', 'С бассейном'],
      address: 'Кирова ул., 70',
      phone: '+7 (812) 28-18-51',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2554 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.5,
      reviewCount: 47,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 6 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 13',
      types: ['Финская сауна'],
      address: 'Победы ул., 75',
      phone: '+7 (812) 90-78-95',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2432 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.2,
      reviewCount: 64,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 10 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Санкт-Петербург 14',
      types: ['Русская баня'],
      address: 'Мира ул., 80',
      phone: '+7 (812) 61-75-14',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1393 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.9,
      reviewCount: 36,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 4 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 15',
      types: ['Русская баня', 'С бассейном'],
      address: 'Советская ул., 85',
      phone: '+7 (812) 78-43-38',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2807 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 57,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Санкт-Петербург 16',
      types: ['Финская сауна'],
      address: 'Советская ул., 90',
      phone: '+7 (812) 23-82-84',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1334 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.4,
      reviewCount: 54,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 13 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 17',
      types: ['Финская сауна'],
      address: 'Советская ул., 95',
      phone: '+7 (812) 37-99-58',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1601 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.5,
      reviewCount: 55,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 12 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 18',
      types: ['Финская сауна'],
      address: 'Мира ул., 100',
      phone: '+7 (812) 62-36-17',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1503 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.8,
      reviewCount: 20,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 6 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Санкт-Петербург 19',
      types: ['Финская сауна'],
      address: 'Ленина ул., 105',
      phone: '+7 (812) 38-63-85',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2606 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.8,
      reviewCount: 58,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 4 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 20',
      types: ['Финская сауна'],
      address: 'Ленина ул., 110',
      phone: '+7 (812) 51-50-32',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2709 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.8,
      reviewCount: 30,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 4 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 21',
      types: ['Русская баня'],
      address: 'Победы ул., 115',
      phone: '+7 (812) 94-21-90',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1241 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.9,
      reviewCount: 43,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 22',
      types: ['Русская баня', 'С бассейном'],
      address: 'Мира ул., 120',
      phone: '+7 (812) 83-94-39',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1518 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 28,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 4 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Санкт-Петербургская баня №23',
      types: ['Финская сауна'],
      address: 'Мира ул., 125',
      phone: '+7 (812) 80-07-38',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1415 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.2,
      reviewCount: 20,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 24',
      types: ['Финская сауна'],
      address: 'Советская ул., 130',
      phone: '+7 (812) 62-55-70',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1917 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 29,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 13 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 25',
      types: ['Русская баня', 'С бассейном'],
      address: 'Кирова ул., 135',
      phone: '+7 (812) 51-00-11',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2987 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.3,
      reviewCount: 53,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 4 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    }
  ],

  // ============= НОВОСИБИРСК (20 бань) =============
  'novosibirsk': [
    {
      name: 'Сауна Новосибирск 1',
      types: ['Русская баня'],
      address: 'Кирова ул., 15',
      phone: '+7 (383) 91-04-08',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1250 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.4,
      reviewCount: 43,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Новосибирск 2',
      types: ['Финская сауна'],
      address: 'Мира ул., 20',
      phone: '+7 (383) 63-45-73',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2219 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.7,
      reviewCount: 20,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 8 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 3',
      types: ['Русская баня'],
      address: 'Кирова ул., 25',
      phone: '+7 (383) 37-16-03',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2199 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.5,
      reviewCount: 34,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Новосибирск 4',
      types: ['Русская баня'],
      address: 'Мира ул., 30',
      phone: '+7 (383) 67-15-98',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1673 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.3,
      reviewCount: 17,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 5',
      types: ['Русская баня'],
      address: 'Мира ул., 35',
      phone: '+7 (383) 57-48-28',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1563 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.3,
      reviewCount: 41,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 6',
      types: ['Финская сауна'],
      address: 'Мира ул., 40',
      phone: '+7 (383) 49-48-47',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1433 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.5,
      reviewCount: 61,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 8 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Новосибирскская баня №7',
      types: ['Финская сауна'],
      address: 'Ленина ул., 45',
      phone: '+7 (383) 82-25-32',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2680 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 22,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 8',
      types: ['Финская сауна'],
      address: 'Кирова ул., 50',
      phone: '+7 (383) 49-92-55',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2952 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.2,
      reviewCount: 26,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 6 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 9',
      types: ['Русская баня'],
      address: 'Победы ул., 55',
      phone: '+7 (383) 51-67-95',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2568 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 25,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 10 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Новосибирскская баня №10',
      types: ['Русская баня', 'С бассейном'],
      address: 'Кирова ул., 60',
      phone: '+7 (383) 30-82-19',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1549 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.9,
      reviewCount: 59,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 11',
      types: ['Русская баня', 'С бассейном'],
      address: 'Мира ул., 65',
      phone: '+7 (383) 74-47-94',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2219 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.3,
      reviewCount: 52,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Новосибирск 12',
      types: ['Русская баня', 'С бассейном'],
      address: 'Победы ул., 70',
      phone: '+7 (383) 90-01-37',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2502 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 21,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 9 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Новосибирск 13',
      types: ['Финская сауна'],
      address: 'Мира ул., 75',
      phone: '+7 (383) 95-85-77',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2659 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 44,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 14',
      types: ['Русская баня'],
      address: 'Победы ул., 80',
      phone: '+7 (383) 71-24-86',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1518 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.5,
      reviewCount: 32,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 10 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Новосибирск 15',
      types: ['Русская баня'],
      address: 'Победы ул., 85',
      phone: '+7 (383) 56-45-75',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2475 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.4,
      reviewCount: 34,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 8 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Новосибирск 16',
      types: ['Русская баня', 'С бассейном'],
      address: 'Советская ул., 90',
      phone: '+7 (383) 58-55-33',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1395 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.5,
      reviewCount: 38,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 17',
      types: ['Русская баня'],
      address: 'Мира ул., 95',
      phone: '+7 (383) 70-12-40',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2905 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 17,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 10 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Новосибирск 18',
      types: ['Финская сауна'],
      address: 'Кирова ул., 100',
      phone: '+7 (383) 49-44-32',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1802 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 17,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 19',
      types: ['Финская сауна'],
      address: 'Мира ул., 105',
      phone: '+7 (383) 76-24-82',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1761 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.3,
      reviewCount: 37,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 4 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 20',
      types: ['Финская сауна'],
      address: 'Победы ул., 110',
      phone: '+7 (383) 73-24-01',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2481 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 51,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 11 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    }
  ],

  // ============= ЕКАТЕРИНБУРГ (20 бань) =============
  'ekaterinburg': [
    {
      name: 'Финская сауна 1',
      types: ['Финская сауна'],
      address: 'Кирова ул., 15',
      phone: '+7 (343) 30-48-91',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2535 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.0,
      reviewCount: 56,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 11 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Екатеринбургская баня №2',
      types: ['Русская баня', 'С бассейном'],
      address: 'Советская ул., 20',
      phone: '+7 (343) 22-79-85',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1722 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.4,
      reviewCount: 54,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 10 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 3',
      types: ['Русская баня', 'С бассейном'],
      address: 'Победы ул., 25',
      phone: '+7 (343) 88-74-78',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2378 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 26,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 11 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 4',
      types: ['Русская баня'],
      address: 'Победы ул., 30',
      phone: '+7 (343) 29-56-55',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2745 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.8,
      reviewCount: 19,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 12 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Екатеринбургская баня №5',
      types: ['Русская баня'],
      address: 'Ленина ул., 35',
      phone: '+7 (343) 70-06-00',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1356 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 47,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 9 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Екатеринбург 6',
      types: ['Финская сауна'],
      address: 'Мира ул., 40',
      phone: '+7 (343) 48-26-73',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1945 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.7,
      reviewCount: 39,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 4 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 7',
      types: ['Финская сауна'],
      address: 'Победы ул., 45',
      phone: '+7 (343) 33-96-80',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1688 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.3,
      reviewCount: 17,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 8',
      types: ['Русская баня'],
      address: 'Кирова ул., 50',
      phone: '+7 (343) 87-86-31',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2037 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.9,
      reviewCount: 60,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 4 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 9',
      types: ['Русская баня', 'С бассейном'],
      address: 'Мира ул., 55',
      phone: '+7 (343) 81-03-26',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2788 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.8,
      reviewCount: 55,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 10 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Екатеринбургская баня №10',
      types: ['Финская сауна'],
      address: 'Победы ул., 60',
      phone: '+7 (343) 56-18-87',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2215 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.4,
      reviewCount: 61,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 4 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 11',
      types: ['Финская сауна'],
      address: 'Ленина ул., 65',
      phone: '+7 (343) 51-00-80',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2709 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.2,
      reviewCount: 51,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 12 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 12',
      types: ['Финская сауна'],
      address: 'Советская ул., 70',
      phone: '+7 (343) 47-15-70',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2614 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.4,
      reviewCount: 49,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 10 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Екатеринбургская баня №13',
      types: ['Русская баня'],
      address: 'Мира ул., 75',
      phone: '+7 (343) 54-80-68',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1677 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.0,
      reviewCount: 28,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 4 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 14',
      types: ['Русская баня', 'С бассейном'],
      address: 'Победы ул., 80',
      phone: '+7 (343) 36-54-43',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1603 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.2,
      reviewCount: 25,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 15',
      types: ['Финская сауна'],
      address: 'Кирова ул., 85',
      phone: '+7 (343) 56-05-77',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2071 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.3,
      reviewCount: 48,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Екатеринбургская баня №16',
      types: ['Финская сауна'],
      address: 'Мира ул., 90',
      phone: '+7 (343) 84-17-61',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1273 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.9,
      reviewCount: 16,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 6 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Екатеринбургская баня №17',
      types: ['Финская сауна'],
      address: 'Ленина ул., 95',
      phone: '+7 (343) 46-05-06',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2580 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.8,
      reviewCount: 18,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 9 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 18',
      types: ['Русская баня'],
      address: 'Мира ул., 100',
      phone: '+7 (343) 76-57-92',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1926 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.8,
      reviewCount: 17,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Екатеринбургская баня №19',
      types: ['Русская баня'],
      address: 'Советская ул., 105',
      phone: '+7 (343) 66-85-97',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1946 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.7,
      reviewCount: 40,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 13 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Екатеринбург 20',
      types: ['Русская баня'],
      address: 'Кирова ул., 110',
      phone: '+7 (343) 46-99-69',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2495 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 56,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    }
  ],

  // ============= КАЗАНЬ (15 бань) =============
  'kazan': [
    {
      name: 'Русская баня 1',
      types: ['Русская баня', 'С бассейном'],
      address: 'Кирова ул., 15',
      phone: '+7 (843) 38-98-63',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2930 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.5,
      reviewCount: 64,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 13 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Казаньская баня №2',
      types: ['Русская баня', 'С бассейном'],
      address: 'Мира ул., 20',
      phone: '+7 (843) 28-84-42',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2755 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.4,
      reviewCount: 51,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 3',
      types: ['Финская сауна'],
      address: 'Мира ул., 25',
      phone: '+7 (843) 21-77-84',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2972 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 5.0,
      reviewCount: 34,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 8 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Казаньская баня №4',
      types: ['Русская баня'],
      address: 'Советская ул., 30',
      phone: '+7 (843) 34-83-71',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1637 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.0,
      reviewCount: 36,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 9 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Банный комплекс 5',
      types: ['Русская баня', 'С бассейном'],
      address: 'Кирова ул., 35',
      phone: '+7 (843) 64-20-03',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1400 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 5.0,
      reviewCount: 54,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 9 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Казань 6',
      types: ['Русская баня'],
      address: 'Ленина ул., 40',
      phone: '+7 (843) 95-72-22',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1955 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.9,
      reviewCount: 35,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Казань 7',
      types: ['Русская баня'],
      address: 'Победы ул., 45',
      phone: '+7 (843) 91-21-59',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1509 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.0,
      reviewCount: 53,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Казань 8',
      types: ['Русская баня', 'С бассейном'],
      address: 'Кирова ул., 50',
      phone: '+7 (843) 48-05-11',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2768 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.1,
      reviewCount: 56,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Казань 9',
      types: ['Финская сауна'],
      address: 'Победы ул., 55',
      phone: '+7 (843) 61-56-71',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1315 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 58,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 11 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Русская баня 10',
      types: ['Русская баня'],
      address: 'Победы ул., 60',
      phone: '+7 (843) 89-17-15',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2172 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.6,
      reviewCount: 45,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 6 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Казань 11',
      types: ['Финская сауна'],
      address: 'Кирова ул., 65',
      phone: '+7 (843) 96-44-84',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2350 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 5.0,
      reviewCount: 60,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 7 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 12',
      types: ['Русская баня'],
      address: 'Кирова ул., 70',
      phone: '+7 (843) 34-39-91',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2628 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.4,
      reviewCount: 33,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 9 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Сауна Казань 13',
      types: ['Русская баня', 'С бассейном'],
      address: 'Мира ул., 75',
      phone: '+7 (843) 77-54-00',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2742 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.5,
      reviewCount: 62,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 8 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Казаньская баня №14',
      types: ['Финская сауна'],
      address: 'Победы ул., 80',
      phone: '+7 (843) 49-21-48',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 2616 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.3,
      reviewCount: 35,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 9 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    },
    {
      name: 'Финская сауна 15',
      types: ['Русская баня', 'С бассейном'],
      address: 'Мира ул., 85',
      phone: '+7 (843) 62-17-43',
      hours: 'Пн-Вс 9:00-22:00',
      price: 'От 1937 ₽/час',
      features: 'Русская баня, веники, чай, комната отдыха',
      rating: 4.5,
      reviewCount: 32,
      topReview: 'Хорошая баня, рекомендую',
      amenities: ['Душевые', 'Комната отдыха', 'Чай'],
      parking: 'Парковка',
      payment: 'Наличные, карты',
      capacity: 'До 5 человек',
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
      additionalServices: [{'name':'Веники','price':'300₽'}],
      bestTime: 'Будни до 18:00',
      booking: 'По телефону',
    }
  ],

};

export default baths;
